models:
  gpt-4o-mini:
    provider: OpenAI
    api_key: OPENAI_API_KEY
    base_url: OPENAI_API_BASE
    max_context: 128000

  gpt-4o:
    provider: OpenAI
    api_key: OPENAI_API_KEY
    base_url: OPENAI_API_BASE
    max_context: 128000

  o1-mini:
    provider: OpenAI
    api_key: OPENAI_API_KEY
    base_url: OPENAI_API_BASE
    max_context: 128000

  o1-mini:
    provider: OpenAI
    api_key: PANDA_API_KEY
    base_url: PANDA_API_BASE
    max_context: 128000

  o1-mini-2024-09-12:
      provider: OpenAI
      api_key: OPENAI_API_KEY
      base_url: OPENAI_API_BASE
      max_context: 128000
 

  o3-mini:
    provider: OpenAI
    api_key: OPENAI_API_KEY
    base_url: OPENAI_API_BASE
    max_context: 200000
    
  gpt-3.5-turbo:
    provider: OpenAI
    api_key: OPENAI_API_KEY
    base_url: OPENAI_API_BASE
    max_context: 16000
    
  claude-3-5-sonnet-20241022:
    provider: Anthropic
    api_key: ANTHROPIC_API_KEY
    base_url: ANTHROPIC_API_BASE
    max_context: 200000

  claude-3-5-haiku-20241022:
    provider: Anthropic
    api_key: ANTHROPIC_API_KEY
    base_url: ANTHROPIC_API_BASE
    max_context: 200000
  
  claude-3-opus-20240229:
    provider: Anthropic
    api_key: ANTHROPIC_API_KEY
    base_url: ANTHROPIC_API_BASE
    max_context: 200000
    
  claude-3-sonnet-20240229:
    provider: Anthropic
    api_key: ANTHROPIC_API_KEY
    base_url: ANTHROPIC_API_BASE
    max_context: 200000
  
  claude-3-haiku-20240307:
    provider: Anthropic
    api_key: ANTHROPIC_API_KEY
    base_url: ANTHROPIC_API_BASE
    max_context: 200000
    
  Qwen/QwQ-32B-Preview:
    provider: OpenAI
    api_key: SILICONFLOW_API_KEY
    base_url: SILICONFLOW_API_BASE
    max_context: 32000
    
  Qwen/Qwen2.5-7B-Instruct:
    provider: OpenAI
    api_key: SILICONFLOW_API_KEY
    base_url: SILICONFLOW_API_BASE
    max_context: 32000

  meta-llama/Llama-3.3-70B-Instruct:
    provider: OpenAI
    api_key: SILICONFLOW_API_KEY
    base_url: SILICONFLOW_API_BASE
    max_context: 32000

  meta-llama/Meta-Llama-3.1-8B-Instruct:
    provider: OpenAI
    api_key: SILICONFLOW_API_KEY
    base_url: SILICONFLOW_API_BASE
    max_context: 32000
    
  deepseek-chat:
    provider: OpenAI
    api_key: DEEPSEEK_API_KEY
    base_url: DEEPSEEK_API_BASE
    max_context: 64000 


  MiniMax-Text-01:
    provider: OpenAI
    api_key: MINIMAX_API_KEY
    base_url: MINIMAX_API_BASE
    max_context: 1000000


  qwen-long:
    provider: OpenAI
    api_key: ALIYUN_API_KEY
    base_url: ALIYUN_API_BASE
    max_context: 1000000

  qwen-plus:
    provider: OpenAI
    api_key: ALIYUN_API_KEY
    base_url: ALIYUN_API_BASE
    max_context: 127000
  
  qwen-max:
    provider: OpenAI
    api_key: ALIYUN_API_KEY
    base_url: ALIYUN_API_BASE
    max_context: 30720

  qwen2.5-7b-instruct:
    provider: OpenAI
    api_key: ALIYUN_API_KEY
    base_url: ALIYUN_API_BASE
    max_context: 128000


  qwen2.5-72b-instruct:
    provider: OpenAI
    api_key: ALIYUN_API_KEY
    base_url: ALIYUN_API_BASE
    max_context: 128000

  qwen-turbo:
    provider: OpenAI
    api_key: ALIYUN_API_KEY
    base_url: ALIYUN_API_BASE
    max_context: 10000000

  qwen-long:
    provider: OpenAI
    api_key: ALIYUN_API_KEY
    base_url: ALIYUN_API_BASE
    max_context: 10000000

  glm-4-air-0111:
    provider: OpenAI
    api_key: GLM_API_KEY
    base_url: GLM_API_BASE
    max_context: 128000
  
  glm-4-plus:
    provider: OpenAI
    api_key: GLM_API_KEY
    base_url: GLM_API_BASE
    max_context: 128000

  meta-llama/Llama-3.3-70B-Instruct-Turbo:
    provider: OpenAI
    api_key: TOGETHER_API_KEY
    base_url: TOGETHER_API_BASE
    max_context: 128000

  meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo:
    provider: OpenAI
    api_key: TOGETHER_API_KEY
    base_url: TOGETHER_API_BASE
    max_context: 128000

  deepseek-ai/DeepSeek-V3:
      provider: OpenAI
      api_key: SILICONFLOW_API_KEY
      base_url: SILICONFLOW_API_BASE
      max_context: 64000

  deepseek-reasoner:
    provider: OpenAI
    api_key: DEEPSEEK_API_KEY
    base_url: DEEPSEEK_API_BASE
    max_context: 57000 
